server:
   port: 9191

spring:
   application:
      name: API-GATEWAY
   cloud:
      gateway:
         routes:
         -  id: CORE-BANKING-SERVICE
            uri: lb://CORE-BANKING-SERVICE
            predicates:
            - Path=/api/v1/account/**
            filters:
            -  name: CircuitBreaker
               args:
                  name: CORE-BANKING-SERVICE
                  fallbackuri: forward:/coreBankingFallBack
         -  id: INTERNET-BANKING-USER-SERVICE
            uri: lb://INTERNET-BANKING-USER-SERVICE
            predicates:
            - Path=/api/v1/bank-user/**

   security:
      oauth2:
         client:
             provider:
                keycloak:
                   token-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
                   authorization-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
                   user-name-attribute: preferred_username
                   user-info-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
                   jwk-set-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
                   user-info-authentication-method: header
             registration:
                internet-banking-core-client:
                   provider: keycloak
                   clientId: ABC-banking-client
                   client-secret: Pude371ztqpnffyZHZKLyfAQMQxMJyCL
                   authorization-grant-type: authorization_code
                   redirect-uri: http://localhost:8083/login/oauth2/code/keycloak
                   scope: openid
         resourceserver:
            jwt:
               jwk-set-uri: ${app.config.keycloak.server-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
               
                   

   

hystrix:
   command:
      fallbackcmd:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 4000

management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

app:
   config:
      keycloak:
         server-url: http://localhost:8083/auth
         realm: ABC-banking-system